spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: jacksparrow
    password: horriblesecret
  security:
    user:
      name: user
      password: $2a$10$lylAQt57JJBszeNu9CPb.eUBbyikDyPkYCRGCfVqTQQamL1UaJWoe
logging:
  file:
    name: movieland.log
config.random.count: 3
config.cache.refreshment.period: 4
config.quote.refreshment.period: 1